name: ocetrac_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandoc
  - pip
  - pip:
      - accessible-pygments
      - babel
      - beautifulsoup4
      - certifi
      - cftime
      - click
      - cloudpickle
      - contourpy
      - cycler
      - dask
      - docutils
      - fonttools
      - fsspec
      - haversine
      - imageio
      - imagesize
      - ipython
      - jinja2
      - jsonschema
      - jupyter-client
      - jupyter-core
      - jupyterlab-pygments
      - kiwisolver
      - lazy-loader
      - markdown-it-py
      - markupsafe
      - matplotlib
      - mistune
      - myst-parser
      - nbclient
      - nbconvert
      - nbformat
      - nbsphinx
      - networkx
      - numpy
      - packaging
      - pandas
      - pandocfilters
      - pillow
      - pydata-sphinx-theme
      - pygments
      - pyparsing
      - python-dateutil
      - pyyaml
      - pyzmq
      - requests
      - scikit-image
      - scipy
      - six
      - snowballstemmer
      - sphinx
      - sphinxcontrib-applehelp
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jsmath
      - sphinxcontrib-qthelp
      - sphinxcontrib-serializinghtml
      - tifffile
      - toolz
      - tornado
      - traitlets
      - typing-extensions
      - urllib3
      - xarray
      - zipp